//Auth signIn Action
export const AUTH_ACTION = 'AUTH_ACTION';
export const AUTH_ACTION_SUCCESS = 'AUTH_ACTION_SUCCESS';
export const AUTH_ACTION_FAIL = 'AUTH_ACTION_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

//Update profile
export const UPDATE_ACTION = 'UPDATE_ACTION';
export const UPDATE_ACTION_SUCCESS = 'UPDATE_ACTION_SUCCESS';
export const UPDATE_ACTION_FAIL = 'UPDATE_ACTION_FAIL';

//Add Posts
export const ADD_POST_ACTION = 'ADD_POST_ACTION';
export const ADD_POST_ACTION_SUCCESS = 'ADD_POST_ACTION_SUCCESS';
export const ADD_POST_ACTION_FAIL = 'ADD_POST_ACTION_FAIL';

//Get Posts
export const GET_POST_ACTION = 'GET_POST_ACTION';
export const GET_POST_ACTION_SUCCESS = 'GET_POST_ACTION_SUCCESS';
export const GET_POST_ACTION_FAIL = 'GET_POST_ACTION_FAIL';

//Delete Posts
export const DELETE_POST_ACTION = 'DELETE_POST_ACTION';
export const DELETE_POST_ACTION_SUCCESS = 'DELETE_POST_ACTION_SUCCESS';
export const DELETE_POST_ACTION_FAIL = 'DELETE_POST_ACTION_FAIL';
